version: '3'
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-end
    ports:
      - "5252:5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "9000:9000"
    depends_on:
      - back-end